### ISSUE TITLE
Prefetch returnes `:timeout`

### ISSUE THREAD

**Issue by linjunpop** [tony612/qiniu#6]
When I prefetch a resource, it throws a `:timeout` exception, but the resource is actually prefetched by Qiniu.

```elixir
** (HTTPoison.Error) :timeout
    (httpoison) lib/httpoison.ex:66: HTTPoison.request!/5
    (qiniu) lib/qiniu/http.ex:24: Qiniu.HTTP.request/4
    (elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:651: Enum.each/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/code.ex:168: Code.eval_string/3
```

The implementation:

```elixir
defmodule HMQ do
  @bucket "hex-mirror"
  @keys ~w(
    registry.ets.gz
    registry.ets.gz.signed
  )

  def prefetch_all do
    @keys
    |> Enum.each(&prefetch/1)
  end

  def prefetch(key) do
    Qiniu.Resource.prefetch("hex-mirror:" <> key)
  end
end
```

**Comment by linjunpop** [comment]
Oh, it's because it takes too long for qiniu to fetch the resource. Not an issue with this package.

**Comment by linjunpop** [comment]
Qiniu response with:

``` json
{
  "error": "httpGet url failed: E502"
}
```
